/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.krisopea.springcors.controller.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RegistrazioneUtenteRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7609387964973772885L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RegistrazioneUtenteRequest\",\"namespace\":\"it.krisopea.springcors.controller.model\",\"fields\":[{\"name\":\"mail\",\"type\":\"string\"},{\"name\":\"password\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RegistrazioneUtenteRequest> ENCODER =
      new BinaryMessageEncoder<RegistrazioneUtenteRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RegistrazioneUtenteRequest> DECODER =
      new BinaryMessageDecoder<RegistrazioneUtenteRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RegistrazioneUtenteRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RegistrazioneUtenteRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RegistrazioneUtenteRequest>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RegistrazioneUtenteRequest to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RegistrazioneUtenteRequest from a ByteBuffer. */
  public static RegistrazioneUtenteRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence mail;
  @Deprecated public java.lang.CharSequence password;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RegistrazioneUtenteRequest() {}

  /**
   * All-args constructor.
   * @param mail The new value for mail
   * @param password The new value for password
   */
  public RegistrazioneUtenteRequest(java.lang.CharSequence mail, java.lang.CharSequence password) {
    this.mail = mail;
    this.password = password;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mail;
    case 1: return password;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mail = (java.lang.CharSequence)value$; break;
    case 1: password = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'mail' field.
   * @return The value of the 'mail' field.
   */
  public java.lang.CharSequence getMail() {
    return mail;
  }

  /**
   * Sets the value of the 'mail' field.
   * @param value the value to set.
   */
  public void setMail(java.lang.CharSequence value) {
    this.mail = value;
  }

  /**
   * Gets the value of the 'password' field.
   * @return The value of the 'password' field.
   */
  public java.lang.CharSequence getPassword() {
    return password;
  }

  /**
   * Sets the value of the 'password' field.
   * @param value the value to set.
   */
  public void setPassword(java.lang.CharSequence value) {
    this.password = value;
  }

  /**
   * Creates a new RegistrazioneUtenteRequest RecordBuilder.
   * @return A new RegistrazioneUtenteRequest RecordBuilder
   */
  public static it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder newBuilder() {
    return new it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder();
  }

  /**
   * Creates a new RegistrazioneUtenteRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RegistrazioneUtenteRequest RecordBuilder
   */
  public static it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder newBuilder(it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder other) {
    return new it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder(other);
  }

  /**
   * Creates a new RegistrazioneUtenteRequest RecordBuilder by copying an existing RegistrazioneUtenteRequest instance.
   * @param other The existing instance to copy.
   * @return A new RegistrazioneUtenteRequest RecordBuilder
   */
  public static it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder newBuilder(it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest other) {
    return new it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder(other);
  }

  /**
   * RecordBuilder for RegistrazioneUtenteRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RegistrazioneUtenteRequest>
    implements org.apache.avro.data.RecordBuilder<RegistrazioneUtenteRequest> {

    private java.lang.CharSequence mail;
    private java.lang.CharSequence password;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mail)) {
        this.mail = data().deepCopy(fields()[0].schema(), other.mail);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.password)) {
        this.password = data().deepCopy(fields()[1].schema(), other.password);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RegistrazioneUtenteRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.mail)) {
        this.mail = data().deepCopy(fields()[0].schema(), other.mail);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.password)) {
        this.password = data().deepCopy(fields()[1].schema(), other.password);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'mail' field.
      * @return The value.
      */
    public java.lang.CharSequence getMail() {
      return mail;
    }

    /**
      * Sets the value of the 'mail' field.
      * @param value The value of 'mail'.
      * @return This builder.
      */
    public it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder setMail(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.mail = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mail' field has been set.
      * @return True if the 'mail' field has been set, false otherwise.
      */
    public boolean hasMail() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mail' field.
      * @return This builder.
      */
    public it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder clearMail() {
      mail = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'password' field.
      * @return The value.
      */
    public java.lang.CharSequence getPassword() {
      return password;
    }

    /**
      * Sets the value of the 'password' field.
      * @param value The value of 'password'.
      * @return This builder.
      */
    public it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder setPassword(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.password = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'password' field has been set.
      * @return True if the 'password' field has been set, false otherwise.
      */
    public boolean hasPassword() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'password' field.
      * @return This builder.
      */
    public it.krisopea.springcors.controller.model.RegistrazioneUtenteRequest.Builder clearPassword() {
      password = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RegistrazioneUtenteRequest build() {
      try {
        RegistrazioneUtenteRequest record = new RegistrazioneUtenteRequest();
        record.mail = fieldSetFlags()[0] ? this.mail : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.password = fieldSetFlags()[1] ? this.password : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RegistrazioneUtenteRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<RegistrazioneUtenteRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RegistrazioneUtenteRequest>
    READER$ = (org.apache.avro.io.DatumReader<RegistrazioneUtenteRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
